version: '2.1'
services:
  opentsdb:
    hostname: otsdb-host
    image: petergrace/opentsdb-docker
    environment:
      - WAITSECS=30
    ports:
      - 4242:4242
      - 60030:60030
    volumes:
      - "./data:/data/hbase"
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider  http://localhost:4242/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  ryu:
    hostname: ryu-host
    image: ryu
    ports:
      - 6653:6653
      - 8080:8080
    environment:
      OTSDB_HOST: "opentsdb"
      OTSDB_METRIC_PREFIX: "oftester"
    depends_on:
      opentsdb:
        condition: service_healthy
